wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1630764646
    t:
      1:
      - 3
      4: 3.6.13
      5: 0.12.1
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 128
buffer_min_size:
  desc: null
  value: 0
buffer_size:
  desc: null
  value: 100000
checkpoint_interval:
  desc: null
  value: 100
eps_decay:
  desc: null
  value: 0.99
eps_end:
  desc: null
  value: 0.01
eps_start:
  desc: null
  value: 1.0
evaluation_env_config:
  desc: null
  value: 0
gamma:
  desc: null
  value: 0.99
hidden_size:
  desc: null
  value: 128
id:
  desc: null
  value: '210904161046'
learning_rate:
  desc: null
  value: 5.0e-05
n_episodes:
  desc: null
  value: 2500
n_evaluation_episodes:
  desc: null
  value: 25
render:
  desc: null
  value: false
restore_replay_buffer:
  desc: null
  value: ''
save_replay_buffer:
  desc: null
  value: false
tau:
  desc: null
  value: 0.001
training_env_config:
  desc: null
  value: 0
update_every:
  desc: null
  value: 8
