wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1630778132
    t:
      1:
      - 3
      2:
      - 3
      4: 3.6.13
      5: 0.12.1
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 128
buffer_min_size:
  desc: null
  value: 0
buffer_size:
  desc: null
  value: 100000
checkpoint_interval:
  desc: null
  value: 10
env_config:
  desc: null
  value: 0
eps_decay:
  desc: null
  value: 0.99
eps_end:
  desc: null
  value: 0.01
eps_start:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.998054629589089
hidden_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.00041429741393648675
malfunction_rate:
  desc: null
  value: 0.02
max_rails_between_cities:
  desc: null
  value: 2
max_rails_in_city:
  desc: null
  value: 3
n_agents:
  desc: null
  value: 2
n_cities:
  desc: null
  value: 2
n_episodes:
  desc: null
  value: 50
n_evaluation_episodes:
  desc: null
  value: 3
observation_max_path_depth:
  desc: null
  value: 30
observation_radius:
  desc: null
  value: 10
observation_tree_depth:
  desc: null
  value: 2
render:
  desc: null
  value: false
restore_replay_buffer:
  desc: null
  value: ''
save_replay_buffer:
  desc: null
  value: false
seed:
  desc: null
  value: 0
tau:
  desc: null
  value: 0.001246143004862745
training_id:
  desc: null
  value: '210904195529'
update_every:
  desc: null
  value: 8
x_dim:
  desc: null
  value: 35
y_dim:
  desc: null
  value: 35
