wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1631635327
    t:
      1:
      - 3
      2:
      - 3
      4: 3.6.13
      5: 0.12.1
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 128
buffer_min_size:
  desc: null
  value: 0
buffer_size:
  desc: null
  value: 100000
checkpoint_interval:
  desc: null
  value: 100
env_config:
  desc: null
  value: 1
eps_decay:
  desc: null
  value: 0.99
eps_end:
  desc: null
  value: 0.01
eps_start:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.93
global_reward:
  desc: null
  value: 5.0
hidden_size_1:
  desc: null
  value: 512
hidden_size_2:
  desc: null
  value: 128
hidden_size_3:
  desc: null
  value: 8
invalid_action_penalty:
  desc: null
  value: -1.0
learning_rate:
  desc: null
  value: 8.0e-05
malfunction_rate:
  desc: null
  value: 0.01
max_rails_between_cities:
  desc: null
  value: 2
max_rails_in_city:
  desc: null
  value: 3
n_agents:
  desc: null
  value: 5
n_cities:
  desc: null
  value: 2
n_episodes:
  desc: null
  value: 500
n_evaluation_episodes:
  desc: null
  value: 5
observation_max_path_depth:
  desc: null
  value: 30
observation_radius:
  desc: null
  value: 10
observation_tree_depth:
  desc: null
  value: 3
render:
  desc: null
  value: true
restore_replay_buffer:
  desc: null
  value: ''
save_replay_buffer:
  desc: null
  value: false
seed:
  desc: null
  value: 0
start_penalty:
  desc: null
  value: 0.0
step_penalty:
  desc: null
  value: -1.5
stop_penalty:
  desc: null
  value: 0.0
tau:
  desc: null
  value: 0.001
training_id:
  desc: null
  value: '210914180204'
update_every:
  desc: null
  value: 8
x_dim:
  desc: null
  value: 35
y_dim:
  desc: null
  value: 35
